main/urls.py
from flask import Blueprint

from . import views, admin_views, errors

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/wechats/', 'wechats', views.list_wechats)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={'fix':True})
main.add_url_rule('/posts/<slug>/preview/', 'post_preview', views.post_detail, defaults={'is_preview':True})
main.add_url_rule('/posts/<slug>/<post_type>/preview/', 'post_general_preview', views.post_detail_general)
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type':'page'})
main.add_url_rule('/wechats/<slug>/', 'wechat_detail', views.post_detail, defaults={'post_type':'wechat'})
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)

blog_admin.add_url_rule('/', view_func=admin_views.AdminIndex.as_view('index'))

blog_admin.add_url_rule('/posts/', view_func=admin_views.PostsList.as_view('posts'))
blog_admin.add_url_rule('/posts/draft/', view_func=admin_views.DraftList.as_view('drafts'))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/posts/<slug>/', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/pages/draft/', view_func=admin_views.DraftList.as_view('page_drafts'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type':'page'})

blog_admin.add_url_rule('/wechats/', view_func=admin_views.PostsList.as_view('wechats'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/wechats/draft/', view_func=admin_views.DraftList.as_view('wechat_drafts'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/new-wechat/', view_func=admin_views.Post.as_view('new_wechat'), defaults={'post_type':'wechat'})

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_views.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<slug>/', view_func=admin_views.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments/', view_func=admin_views.Comment.as_view('comments'))
blog_admin.add_url_rule('/posts/comments/approved/', view_func=admin_views.Comment.as_view('comments_approved'), defaults={'status':'approved'})
blog_admin.add_url_rule('/posts/comments/spam/', view_func=admin_views.Comment.as_view('comments_spam'), defaults={'status':'spam'})
blog_admin.add_url_rule('/posts/comments/<pk>/action/', view_func=admin_views.Comment.as_view('comment_action'))
blog_admin.add_url_rule('/posts/comments/import/', view_func=admin_views.ImportCommentView.as_view('import_comments'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view('su_posts'))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.add_url_rule('/su/widgets/', view_func=admin_views.WidgetList.as_view('su_widgets'))
blog_admin.add_url_rule('/su/widgets/create/', view_func=admin_views.Widget.as_view('su_widget'))
blog_admin.add_url_rule('/su/widgets/<pk>/', view_func=admin_views.Widget.as_view('su_widget_edit'))
blog_admin.add_url_rule('/su/export/', view_func=admin_views.SuExportView.as_view('su_export'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)


main/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask_mongoengine.wtf import model_form
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, TextAreaField, HiddenField, RadioField, FileField, IntegerField
from wtforms import widgets, ValidationError
from wtforms.validators import Required, Length, Email, Regexp, EqualTo, URL, Optional

from . import models


class PostForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    slug = StringField('Slug', validators=[Required()])
    raw = TextAreaField('Content')
    abstract = TextAreaField('Abstract')
    category = StringField('Category')
    tags_str = StringField('Tags')
    post_id = HiddenField('post_id')
    post_type = HiddenField('post_type')
    from_draft = HiddenField('from_draft')

    def validate_slug(self, field):
        if self.from_draft.data and self.from_draft.data == 'true':
            posts = models.Draft.objects.filter(slug=field.data)
        else:
            posts = models.Post.objects.filter(slug=field.data)
        if posts.count() > 0:
            if not self.post_id.data or str(posts[0].id) != self.post_id.data:
                raise ValidationError('slug already used')

SuPostForm = model_form(models.Post, exclude=['pub_time', 'update_time', 'content_html', 'category', 'tags', 'post_type'])


class WidgetForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    content_type = RadioField('Content Type', choices=[('markdown', 'markdown'), ('html', 'html')], default='html')
    priority = IntegerField(default=1000000)


class CommentForm(FlaskForm):
    email = StringField('* Email', validators=[Required(), Length(1,128), Email()])
    author = StringField('* Name', validators=[Required(), Length(1,128)])
    homepage = StringField('Homepage', validators=[URL(), Optional()])
    content = TextAreaField('* Comment <small><span class="label label-info">markdown</span></small>', validators=[Required()])
    comment_id = HiddenField('comment_id')


class SessionCommentForm(FlaskForm):
    email = HiddenField('* Email')
    author = HiddenField('* Name')
    homepage = HiddenField('Homepage')
    content = TextAreaField('* Comment', validators=[Required()])
    comment_id = HiddenField('comment_id')


class ImportCommentForm(FlaskForm):
    content = TextAreaField('Content')
    json_file = FileField('Json File')
    import_format = RadioField('Import Format', choices=[('text', 'text'), ('file', 'file')], default='text')

main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from urllib.parse import urljoin
from datetime import datetime, timedelta

from flask import request, redirect, render_template, url_for, abort, flash, g, session
from flask import current_app, make_response
from flask.views import MethodView

# from flask.ext.login import login_required, current_user
from flask_login import login_required, current_user

from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q

from . import models, signals, forms
from accounts.models import User
from accounts.permissions import admin_permission, editor_permission, writer_permission, reader_permission
from SlqBlog.config import SlqBlogSettings

PER_PAGE = SlqBlogSettings['pagination'].get('per_page', 10)
ARCHIVE_PER_PAGE = SlqBlogSettings['pagination'].get('archive_per_page', 10)


def get_base_data():
    pages = models.Post.objects.filter(post_type='page', is_draft=False)
    blog_meta = SlqBlogSettings['blog_meta']
    data = {'blog_meta': blog_meta, 'pages': pages}
    return data


def index():
    return 'Hello'


def list_posts():
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    # group by aggregate
    category_cursor = models.Post._get_collection().aggregate([
        {'$group':
             {'_id': {'category': '$category'},
              'name': {'$first': '$category'},
              'count': {'$sum': 1},
              }
         }
    ])

    widgets = models.Widget.objects(allow_post_types='post')
    # exp: convert all posts to posts in pages
    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/index.html', **data)


def list_wechats():
    posts = models.Post.objects.filter(post_type='wechat', is_draft=False).order_by('-pub_time')

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    widgets = models.Widget.objects(allow_post_types='wechat')

    data = get_base_data()
    data['posts'] = posts
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/wechat_list.html', **data)


def post_detail(slug, post_type='post', fix=False, is_preview=False):
    if is_preview:
        if not g.identity.can(reader_permission):
            abort(401)
        post = models.Draft.objects.get_or_404(slug=slug, post_type=post_type)
    else:
        post = models.Post.objects.get_or_404(slug=slug,
                                              post_type=post_type) if not fix else models.Post.objects.get_or_404(
            fix_slug=slug, post_type=post_type)

    # this block is abandoned
    if post.is_draft and current_user.is_anonymous:
        abort(404)

    data = get_base_data()
    data['post'] = post
    data['post_type'] = post_type

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'author': session.get('author'), 'email': session.get('email'), 'homepage': session.get('homepage'),}
        form = forms.CommentForm(**obj)
        # print session.get('email')

    if request.form.get('slq-comment') and form.validate_on_submit():
        slqblog_create_comment(form, post)
        url = '{0}#comment'.format(url_for('main.post_detail', slug=slug))
        msg = 'Succeed to comment, and it will be displayed when the administrator reviews it.'
        flash(msg, 'success')
        return redirect(url)

    data['allow_donate'] = SlqBlogSettings['donation']['allow_donate']
    data['donation_msg'] = SlqBlogSettings['donation']['donation_msg']

    data['display_wechat'] = SlqBlogSettings['wechat']['display_wechat']
    data['wechat_msg'] = SlqBlogSettings['wechat']['wechat_msg']

    data['display_copyright'] = SlqBlogSettings['copyright']['display_copyright']
    data['copyright_msg'] = SlqBlogSettings['copyright']['copyright_msg']

    data['allow_comment'] = SlqBlogSettings['blog_comment']['allow_comment']
    if data['allow_comment']:
        comment_type = SlqBlogSettings['blog_comment']['comment_type']
        comment_shortname = SlqBlogSettings['blog_comment']['comment_opt'][comment_type]
        comment_func = get_comment_func(comment_type)
        data['comment_html'] = comment_func(slug, post.title, request.base_url, comment_shortname,
                                            form=form) if comment_func else ''

    data['allow_share_article'] = SlqBlogSettings['allow_share_article']
    # if data['allow_share_article']:
    #     data['share_html'] = jiathis_share()

    # send signal
    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    templates = {
        'post': 'main/post.html',
        'page': 'main/post.html',
        'wechat': 'main/wechat_detail.html',
    }

    return render_template(templates[post_type], **data)


def post_preview(slug, post_type='post'):
    return post_detail(slug=slug, post_type=post_type, is_preview=True)


def post_detail_general(slug, post_type):
    is_preview = request.args.get('is_preview', 'false')
    is_preview = True if is_preview.lower() == 'true' else False
    return post_detail(slug=slug, post_type=post_type, is_preview=is_preview)


def author_detail(username):
    author = User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(post_type='post', is_draft=False, author=author).order_by('-pub_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['user'] = author
    data['posts'] = posts
    # data['category_cursor'] = category_cursor
    # data['cur_tag'] = cur_tag
    # data['tags'] = tags
    # data['keywords'] = keywords

    return render_template('main/author.html', **data)


def get_comment_func(comment_type):
    # if comment_type == 'duoshuo':
    #     return duoshuo_comment
    # else:
    #     return None
    comment_func = {
        'slqblog': slqblog_comment,
        'duoshuo': duoshuo_comment,
    }

    return comment_func.get(comment_type)


def slqblog_comment(post_id, post_title, post_url, comment_shortname, form=None, *args, **kwargs):
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_slug=post_id, status='approved').order_by('pub_time')
    # print comments[0].get_gavatar_url()
    # if not form:
    #     if session.get('author'):
    #         print 'session'
    #         return 'session'
    #         data = {'author': session['author'], 'email': session['email'],'homepage': session['homepage'],}
    #         form = forms.SessionCommentForm(obj=data)
    #     else:
    #         print 'no session'
    #         return 'no session'
    #         form = forms.CommentForm(obj=request.form)
    data = {
        'form': form,
        'comments': comments,
        'slug': post_id,
    }
    return render_template(template_name, **data)


def slqblog_create_comment(form, post):
    comment = models.Comment()
    comment.author = form.author.data.strip()
    comment.email = form.email.data.strip()
    comment.homepage = form.homepage.data.strip() or None
    comment.post_slug = post.slug
    comment.post_title = post.title
    comment.md_content = form.content.data.strip()
    comment.save()

    session['author'] = form.author.data.strip()
    session['email'] = form.email.data.strip()
    session['homepage'] = form.homepage.data.strip()


def duoshuo_comment(post_id, post_title, post_url, duoshuo_shortname, *args, **kwargs):
    '''
    Create duoshuo script by params
    '''
    template_name = 'main/misc/duoshuo.html'
    data = {
        'duoshuo_shortname': duoshuo_shortname,
        'post_id': post_id,
        'post_title': post_title,
        'post_url': post_url,
    }

    return render_template(template_name, **data)


# def jiathis_share():
#     '''
#     Create duoshuo script by params
#     '''
#     template_name = 'main/misc/jiathis_share.html'

#     return render_template(template_name)

def archive():
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)


templates/main/archive.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://omyahpaum.bkt.clouddn.com/blog/20170324/230941164.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.subtitle }} <a href="{{ url_for('main.recent_feed') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="row">
                {% for post in posts.items %}
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                      <!-- <img src="..." alt="..."> -->
                      <div class="caption">
                        <h3><a href="{{ url_for('main.post_detail', slug=post.slug) }}">{{ post.title }}</a></h3><hr>
                        <p><strong>Abstract: </strong>{{ post.abstract }}</p>
                        <p><strong>Author: </strong>{{ post.author }}</p>
                        <p><strong>Date: </strong>{{ post.pub_time.strftime('%Y/%m/%d') }}</p>
                        
                      </div>
                    </div>          
                </div>
                {% endfor %}
            </div>

            <div class="row">
                {% import '_pagination.html' as pagination %}
                {{ pagination.render_pagination(posts) }}
            </div>
        </div>

    </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}

templates/main/post.html
{% extends 'base.html' %}
{% block title %} {{ post.title }} {% endblock %}

{% block custom_head %}
    <link href="{{ url_for('static', filename='css/share.min.css') }}" rel="stylesheet">
{% endblock %}

{% block header %}
<header class="intro-header" style="background-image: url('http://omyahpaum.bkt.clouddn.com/blog/20170324/230610559.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>{{ post.title }}</h1>
                        <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2> -->
                        <span class="meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.pub_time.strftime('%Y/%m/%d %H:%M:%S') }}</span>
                        {% if post.category%}
                        <span class="meta">Category: <a href="{{ url_for('main.index') }}?category={{ post.category }}">{{ post.category }}</a></span>
                        {% endif %}
                        <span class="meta">Tags:
                            {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
{% block main %}
<div class="container">
    <article>
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{post.content_html|safe}}
                </div>
            </div>

        {% if not post.post_type=='page' %}
            {% if display_copyright %}
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <hr>
                    <p><strong>{{ copyright_msg }}</strong></p>
                <hr>
                </div>

            </div>
            {% endif %}
            <br>
            {% if allow_share_article %}
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="share-component" data-sites="weibo,wechat,douban,twitter,qq,google,facebook,linkedin"></div>
                </div>


            </div>
            {% endif %}
            <br>
            {% if allow_donate %}
            <div class="row">
                <!-- donate -->
                <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <hr>
                    <p>{{ donation_msg }}</p>
<script language="javascript" type="text/javascript">
    /***
     *功能：隐藏和显示div
     * *参数divDisplay：html标签id
     ***/
    function click_a(divDisplay)
    {


        if(document.getElementById(divDisplay).style.display != "block")
        {
            document.getElementById("wechatpay").style.display = "none";
            document.getElementById("alipay").style.display = "none";
            document.getElementById("paypal").style.display = "none";
            document.getElementById(divDisplay).style.display = "block";
        }
        else
        {
            document.getElementById(divDisplay).style.display = "none";
        }
    }
</script>
<style>
.oneline ul{list-style:none;}
.oneline li{float:left;width:100px;background:#A5DEE4;margin:2px;line-height:30px;}
.oneline a{display:block;text-align:center;height:30px;}
.oneline a:link{color:#666;background:#CCC no-repeat 5px 12px;text-decoration:none;}
.oneline a:visited{color:#666;text-decoration:underline;}
.oneline a:hover{color:#FFF; font-weight:bold;text-decoration:none;background:#305A56 no-repeat 5px 12px;}
</style>
                     <div class="oneline">
                         <ul>
                             <li><a onclick="return click_a('wechatpay')" style="cursor:pointer;">微信</a></li>
                             <li><a onclick="return click_a('alipay')" style="cursor:pointer;">支付宝</a></li>
                             <li><a onclick="return click_a('paypal')" style="cursor:pointer;">PayPal</a></li>
                         </ul>
                         <br>
                     </div>
                    <br>

                     <div id="wechatpay" style="display:none;">
                         <img src="http://omyahpaum.bkt.clouddn.com/blog/20170324/014132428.png" title="wechatpay">
                     </div>
                     <div id="alipay" style="display:none;">
                         <img src="http://omyahpaum.bkt.clouddn.com/blog/20170324/013532726.png" title="alipay">
                     </div>
                     <div id="paypal" style="display:none;">
                         <p>适合国际友人，无论有没有PayPal账户，都可以点击赞助：</p>
                         <br>
                         <a href="https://www.paypal.me/shawnlinq" target="_blank"><img src="http://omyahpaum.bkt.clouddn.com/blog/20170324/015114793.png" style="cursor:pointer;"></a>
                     </div>



                </div>
            </div>
            <br>

            {% endif %}

            {% if display_wechat %}
            <div class="row">
                <!-- donate -->
                <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <hr>
                    <p><i class="fa fa-weixin" aria-hidden="true"></i><a onclick="return click_a('wechat')" style="cursor:pointer;">{{ wechat_msg }} </a></p>
                    <div id="wechat" style="display:none;">
                    <img src="http://omyahpaum.bkt.clouddn.com/blog/20170317/163519898.jpg" title="ShawnView">
                    </div>
                </div>
                
            </div>
            {% endif %}
            
        {% endif %}
            
        <!-- </div> -->
    </article>
    <br>
    <hr>
    {% if allow_comment %}
        <article>
            <!-- <div class="container"> -->
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        {{ comment_html|safe }}
                    </div>
                </div>
            <!-- </div> -->
        </article>
    {% endif %}
</div>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/share.min.js') }}"></script>
<script type="text/javascript">
    $('table').addClass('table');
    $('#btn_donate').on('click', function(event){
        if($('#donate_guide').hasClass('hidden'))
            $('#donate_guide').removeClass('hidden');
        else
            $('#donate_guide').addClass('hidden');
        return false
    });
    
    
</script>
{% endblock %}

templates/main/wechat_list.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ blog_meta.wechat_name | safe }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.wechat_subtitle }} <a href="{{ url_for('main.recent_feed') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2 col-md-8 col-md-offset-1">
            {% for post in posts.items %}
            <div class="post-preview">
                <a href="{{ url_for('main.wechat_detail', slug=post.slug) }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                </a>
                <p class="post-subtitle">
                    {{ post.abstract }}
                </p>
                <p class="post-meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.pub_time.strftime('%Y/%m/%d %H:%M:%S') }}</p>
                <p class="post-meta">Tags:
                            {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                </p>
            </div>
            {% if not loop.last %}
            <hr>
            {% endif %}
            {% else %}
                <p class="post-subtitle">
                    No articles found here
                </p>
            {% endfor %}
            <!-- Pager -->
            <ul class="pager">
                {% if posts.has_next %}
                <li class="next">
                    <a href="?page={{ posts.next_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Older Posts &rarr;</a>
                </li>
                {% endif %}
                {% if posts.has_prev %}
                    <li class="next"><a href="?page={{ posts.prev_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Previous Posts</a></li>
                {% endif %}
            </ul>
        </div>
        

        <div class="col-lg-3 col-md-2">
            <h3>Search</h3><hr/>
            <form id="search-form">
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-search"></i></div>
                  <input type="text" class="form-control" id="search" name="keywords" placeholder="search" value="{% if keywords %}{{ keywords }}{% endif %}">
                </div>
              </div>
              <!-- <button type="submit" class="btn btn-default">Transfer cash</button> -->
            </form>
            <!-- <hr> -->
            <br>

            <h3>Tags</h3><hr/>
            {% for tag in tags %}
                <a href="?tag={{tag}}" class="post-tag">
                    {% if tag == cur_tag %}
                    <span class="label label-primary">
                        {{ tag }}
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                    </span>
                    
                    {% else %}
                    <span class="label label-default">
                        {{ tag }}
                    </span>
                    
                    {% endif %}
                    
                </a>
                &nbsp;
            {% endfor %}
            
            
            {% for widget in widgets %}
            <h3>{{ widget.title | safe }}</h3><hr/>
            <div class="list-group">
                {{ widget.html_content | safe }}
            </div>
            {% endfor %}

                        
        </div>
    </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}