main/urls.py
from flask import Blueprint

from . import views, admin_views, errors

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/wechats/', 'wechats', views.list_wechats)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={'fix':True})
main.add_url_rule('/posts/<slug>/preview/', 'post_preview', views.post_detail, defaults={'is_preview':True})
main.add_url_rule('/posts/<slug>/<post_type>/preview/', 'post_general_preview', views.post_detail_general)
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type':'page'})
main.add_url_rule('/wechats/<slug>/', 'wechat_detail', views.post_detail, defaults={'post_type':'wechat'})
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)

blog_admin.add_url_rule('/', view_func=admin_views.AdminIndex.as_view('index'))

blog_admin.add_url_rule('/posts/', view_func=admin_views.PostsList.as_view('posts'))
blog_admin.add_url_rule('/posts/draft/', view_func=admin_views.DraftList.as_view('drafts'))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/posts/<slug>/', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/pages/draft/', view_func=admin_views.DraftList.as_view('page_drafts'), defaults={'post_type':'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type':'page'})

blog_admin.add_url_rule('/wechats/', view_func=admin_views.PostsList.as_view('wechats'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/wechats/draft/', view_func=admin_views.DraftList.as_view('wechat_drafts'), defaults={'post_type':'wechat'})
blog_admin.add_url_rule('/new-wechat/', view_func=admin_views.Post.as_view('new_wechat'), defaults={'post_type':'wechat'})

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_views.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<slug>/', view_func=admin_views.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments/', view_func=admin_views.Comment.as_view('comments'))
blog_admin.add_url_rule('/posts/comments/approved/', view_func=admin_views.Comment.as_view('comments_approved'), defaults={'status':'approved'})
blog_admin.add_url_rule('/posts/comments/spam/', view_func=admin_views.Comment.as_view('comments_spam'), defaults={'status':'spam'})
blog_admin.add_url_rule('/posts/comments/<pk>/action/', view_func=admin_views.Comment.as_view('comment_action'))
blog_admin.add_url_rule('/posts/comments/import/', view_func=admin_views.ImportCommentView.as_view('import_comments'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view('su_posts'))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.add_url_rule('/su/widgets/', view_func=admin_views.WidgetList.as_view('su_widgets'))
blog_admin.add_url_rule('/su/widgets/create/', view_func=admin_views.Widget.as_view('su_widget'))
blog_admin.add_url_rule('/su/widgets/<pk>/', view_func=admin_views.Widget.as_view('su_widget_edit'))
blog_admin.add_url_rule('/su/export/', view_func=admin_views.SuExportView.as_view('su_export'))

blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)


main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from urllib.parse import urljoin
from datetime import datetime, timedelta

from flask import request, redirect, render_template, url_for, abort, flash, g, session
from flask import current_app, make_response
from flask.views import MethodView

# from flask.ext.login import login_required, current_user
from flask_login import login_required, current_user

from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q

from . import models, signals, forms
from accounts.models import User
from accounts.permissions import admin_permission, editor_permission, writer_permission, reader_permission
from SlqBlog.config import SlqBlogSettings

PER_PAGE = SlqBlogSettings['pagination'].get('per_page', 10)
ARCHIVE_PER_PAGE = SlqBlogSettings['pagination'].get('archive_per_page', 10)


def get_base_data():
    pages = models.Post.objects.filter(post_type='page', is_draft=False)
    blog_meta = SlqBlogSettings['blog_meta']
    data = {'blog_meta': blog_meta, 'pages': pages}
    return data


def index():
    return 'Hello'


def list_posts():
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    # group by aggregate
    category_cursor = models.Post._get_collection().aggregate([
        {'$group':
             {'_id': {'category': '$category'},
              'name': {'$first': '$category'},
              'count': {'$sum': 1},
              }
         }
    ])

    widgets = models.Widget.objects(allow_post_types='post')
    # exp: convert all posts to posts in pages
    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/index.html', **data)


def list_wechats():
    posts = models.Post.objects.filter(post_type='wechat', is_draft=False).order_by('-pub_time')

    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    widgets = models.Widget.objects(allow_post_types='wechat')

    data = get_base_data()
    data['posts'] = posts
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    data['widgets'] = widgets

    return render_template('main/wechat_list.html', **data)


def post_detail(slug, post_type='post', fix=False, is_preview=False):
    if is_preview:
        if not g.identity.can(reader_permission):
            abort(401)
        post = models.Draft.objects.get_or_404(slug=slug, post_type=post_type)
    else:
        post = models.Post.objects.get_or_404(slug=slug,
                                              post_type=post_type) if not fix else models.Post.objects.get_or_404(
            fix_slug=slug, post_type=post_type)

    # this block is abandoned
    if post.is_draft and current_user.is_anonymous:
        abort(404)

    data = get_base_data()
    data['post'] = post
    data['post_type'] = post_type

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'author': session.get('author'), 'email': session.get('email'), 'homepage': session.get('homepage'),}
        form = forms.CommentForm(**obj)
        # print session.get('email')

    if request.form.get('slq-comment') and form.validate_on_submit():
        slqblog_create_comment(form, post)
        url = '{0}#comment'.format(url_for('main.post_detail', slug=slug))
        msg = 'Succeed to comment, and it will be displayed when the administrator reviews it.'
        flash(msg, 'success')
        return redirect(url)

    data['allow_donate'] = SlqBlogSettings['donation']['allow_donate']
    data['donation_msg'] = SlqBlogSettings['donation']['donation_msg']

    data['display_wechat'] = SlqBlogSettings['wechat']['display_wechat']
    data['wechat_msg'] = SlqBlogSettings['wechat']['wechat_msg']

    data['display_copyright'] = SlqBlogSettings['copyright']['display_copyright']
    data['copyright_msg'] = SlqBlogSettings['copyright']['copyright_msg']

    data['allow_comment'] = SlqBlogSettings['blog_comment']['allow_comment']
    if data['allow_comment']:
        comment_type = SlqBlogSettings['blog_comment']['comment_type']
        comment_shortname = SlqBlogSettings['blog_comment']['comment_opt'][comment_type]
        comment_func = get_comment_func(comment_type)
        data['comment_html'] = comment_func(slug, post.title, request.base_url, comment_shortname,
                                            form=form) if comment_func else ''

    data['allow_share_article'] = SlqBlogSettings['allow_share_article']
    # if data['allow_share_article']:
    #     data['share_html'] = jiathis_share()

    # send signal
    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    templates = {
        'post': 'main/post.html',
        'page': 'main/post.html',
        'wechat': 'main/wechat_detail.html',
    }

    return render_template(templates[post_type], **data)


def post_preview(slug, post_type='post'):
    return post_detail(slug=slug, post_type=post_type, is_preview=True)


def post_detail_general(slug, post_type):
    is_preview = request.args.get('is_preview', 'false')
    is_preview = True if is_preview.lower() == 'true' else False
    return post_detail(slug=slug, post_type=post_type, is_preview=is_preview)


def author_detail(username):
    author = User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(post_type='post', is_draft=False, author=author).order_by('-pub_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['user'] = author
    data['posts'] = posts
    # data['category_cursor'] = category_cursor
    # data['cur_tag'] = cur_tag
    # data['tags'] = tags
    # data['keywords'] = keywords

    return render_template('main/author.html', **data)


def get_comment_func(comment_type):
    # if comment_type == 'duoshuo':
    #     return duoshuo_comment
    # else:
    #     return None
    comment_func = {
        'slqblog': slqblog_comment,
        'duoshuo': duoshuo_comment,
    }

    return comment_func.get(comment_type)


def slqblog_comment(post_id, post_title, post_url, comment_shortname, form=None, *args, **kwargs):
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_slug=post_id, status='approved').order_by('pub_time')
    # print comments[0].get_gavatar_url()
    # if not form:
    #     if session.get('author'):
    #         print 'session'
    #         return 'session'
    #         data = {'author': session['author'], 'email': session['email'],'homepage': session['homepage'],}
    #         form = forms.SessionCommentForm(obj=data)
    #     else:
    #         print 'no session'
    #         return 'no session'
    #         form = forms.CommentForm(obj=request.form)
    data = {
        'form': form,
        'comments': comments,
        'slug': post_id,
    }
    return render_template(template_name, **data)


def slqblog_create_comment(form, post):
    comment = models.Comment()
    comment.author = form.author.data.strip()
    comment.email = form.email.data.strip()
    comment.homepage = form.homepage.data.strip() or None
    comment.post_slug = post.slug
    comment.post_title = post.title
    comment.md_content = form.content.data.strip()
    comment.save()

    session['author'] = form.author.data.strip()
    session['email'] = form.email.data.strip()
    session['homepage'] = form.homepage.data.strip()


def duoshuo_comment(post_id, post_title, post_url, duoshuo_shortname, *args, **kwargs):
    '''
    Create duoshuo script by params
    '''
    template_name = 'main/misc/duoshuo.html'
    data = {
        'duoshuo_shortname': duoshuo_shortname,
        'post_id': post_id,
        'post_title': post_title,
        'post_url': post_url,
    }

    return render_template(template_name, **data)


# def jiathis_share():
#     '''
#     Create duoshuo script by params
#     '''
#     template_name = 'main/misc/jiathis_share.html'

#     return render_template(template_name)

def archive():
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)


templates/_form.html
{% macro render(form) -%}

{% for field in form %}
  {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
    {{ field() }}
  {% elif field.type == "BooleanField" %}
  <div class="checkbox">
    <label>
      {{ field() }} {{ field.label }}
    </label>
  </div>

  {% elif field.type == "RadioField" %}
  {{ field.label }}
    {% for subfield in field %}
      <div class="radio">
        <label>{{ subfield }} {{ subfield.label }}</label>
      </div>
  {% endfor %}
    

  {% else %}
    <div class="clearfix {% if field.errors %}has-error{% endif %} form-group">

      {{ field.label }}
        {% if field.type == "TextAreaField" %}
          {{ field(class_="form-control", rows=10) }}
        {% else %}
          {{ field(class_="form-control") }}
        {% endif %}
        {% if field.errors or field.help_text %}
          <span class="help-block">
          {% if field.errors %}
            {{ field.errors|join(' ') }}
          {% else %}
            {{ field.help_text }}
          {% endif %}
          </span>
        {% endif %}
    </div>
  {% endif %}
{% endfor %}

{% endmacro %}

templates/_msg.html
{% macro render_msg() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash_msg">
    {% for category, message in messages %}
      {% if category == 'message' %}
        {% set category='info' %}
      {% endif %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert" style="margin-bottom: 0px">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% endmacro %}

templates/_pagination.html
{% macro render_pagination(pagination) %}
  <nav>
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
            <span aria-hidden="true">&laquo;</span>
        </li>
      {% else %}
        <li>
        <a href="?page={{ pagination.prev_num }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
      {% endif %}
    
      {%- for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="?page={{ page }}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <!-- <span class=ellipsis>…</span> -->
          <li><a href="#">...</a></li>
        {% endif %}
      {%- endfor %}

      {% if not pagination.has_next %}
        <li class="disabled">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li>
          <a href="?page={{ pagination.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}      
    </ul>
  </nav>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    {% if post %}
    <meta name="title" content="{{ post.title }} | {{ blog_meta.name }}">
    <meta name="description" content="{{ post.abstract }}">
    <meta name="author" content="{{ post.author.username }}">
    <meta name="keywords" content="{{ post.tags|join(',') }}">
    {% else %}
    <meta name="title" content="{{ blog_meta.name }}">
    <meta name="description" content="{{ blog_meta.description }}">
    <meta name="author" content="{{ blog_meta.owner }}">
    <meta name="keywords" content="{{ blog_meta.keywords }}">
    {% endif %}
    <!-- 从环境导入搜索验证凭证失败
    <meta name="google-site-verification" content="{{ blog_meta.google_site_verification }}" />
    <meta name="baidu-site-verification" content="{{ blog_meta.baidu_site_verification }}" />
    <meta name="sogou_site_verification" content="{{ blog_meta.sogou_site_verification }}" />
    <meta name="msvalidate.01" content="{{ blog_meta.bing_site_verification }}" />
    <meta name="360_site_verification" content="{{ blog_meta.get360_site_verification }}" />  -->

    <!-- 直接使用静态注入验证凭证 -->
    <meta name="baidu-site-verification" content="CHGIj3UoVk" />
    <meta name="sogou_site_verification" content="CJqu0SLnt0" />
    <meta name="google-site-verification" content="nd-uzkrk3H1c_Be19bYQsmpbpDwWH5dIigRE9mUpNz8" />
    <meta name="360-site-verification" content="b4a1b4b922c4169b6e73e7dbc768d54c" />
    <meta name="msvalidate.01" content="342C90C1E0E3B92988AC6C1A01179D10" />

    <title>{% block title %}SlQ Blog{% endblock %}</title>

    <!-- Bootstrap Core CSS -->

    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">

    <!-- <link href="http://cdn.staticfile.org/twitter-bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/clean-blog.css') }}" rel="stylesheet">
    <!-- <link rel="stylesheet" href="//cdn.bootcss.com/startbootstrap-clean-blog/3.3.7/css/clean-blog.min.css"> -->
    <link href="{{ url_for('static', filename='css/slqblog.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.bootcss.com/highlight.js/9.9.0/styles/default.min.css">

    <link href="{{ url_for('main.recent_feed') }}"
      rel="alternate"
      title="Recent Changes" 
      type="application/atom+xml">

    {% block custom_head %}{% endblock %}
    <style> html{display : none ; } </style> 
    <script>
    if( self == top ) {
              document.documentElement.style.display = 'block' ;
       } else {
           top.location = self.location ;
       }
    </script>

    <!-- Custom Fonts -->
    <!-- <link href="http://libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">SlQ Blog</a> 
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('main.recent_feed') }}" target="_blank">RSS</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.archive') }}">全部文章</a>
                    </li>
                    <li>
                        <a href="{{ url_for('static', filename='timeline.html') }}">网站纪事</a>
                    </li>
                   
                    {% for page in pages %}
                    <li>
                        <a href="{{ url_for('main.page_detail', slug=page.slug) }}">{{ page.slug }}</a>
                    </li>
                    {% endfor %}

                    <li>
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('blog_admin.index') }}">{{ current_user.username }}</a>
                        {% endif %}
                    </li>
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <!-- Main Content -->
    {%block main %}{% endblock %}
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('main.recent_feed') }}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/shawnlinq/SlqBlog2" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; SlQ Blog 2017  |  <span id="busuanzi_container_site_pv">你是第<span id="busuanzi_value_site_pv"></span>位来访者</span></p>
                    <p></p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="//cdn.bootcss.com/highlight.js/9.9.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <!-- busuanzi container -->
    <script async src="//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>
    <!-- google analytics -->
    <script>
       (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

       ga('create', 'UA-96177669-1', 'auto');
       ga('send', 'pageview');
    </script>
    <!-- end google analytics -->
    {% block js %}
    {% endblock %}
</body>
</html>